- job:
    name: oslo.cache-tempest-full-py3-memcached-pool
    parent: tempest-full-py3
    voting: false
    description: |
      Base integration test with memcache_pool backend.
    vars:
      devstack_localrc:
        CACHE_BACKEND: oslo_cache.memcache_pool

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-lower-constraints-jobs
      - openstack-python3-train-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - oslo.cache-tempest-full-py3-memcached-pool
